# Generated by Django 4.2.7 on 2025-10-09 01:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'db_table': 'Categorias',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='RUT')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre')),
                ('correo', models.EmailField(blank=True, max_length=100, null=True, verbose_name='Correo Electrónico')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('numero', models.CharField(max_length=10, verbose_name='Número')),
                ('depto', models.CharField(blank=True, max_length=10, null=True, verbose_name='Departamento')),
                ('comuna', models.CharField(max_length=100, verbose_name='Comuna')),
                ('region', models.CharField(max_length=100, verbose_name='Región')),
                ('codigo_postal', models.CharField(blank=True, max_length=45, null=True, verbose_name='Código Postal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
            ],
            options={
                'verbose_name': 'Dirección',
                'verbose_name_plural': 'Direcciones',
                'db_table': 'Direccion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Nutricional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calorias', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Calorías')),
                ('proteinas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Proteínas (g)')),
                ('grasas', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Grasas (g)')),
                ('carbohidratos', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Carbohidratos (g)')),
                ('azucares', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Azúcares (g)')),
                ('sodio', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Sodio (mg)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
            ],
            options={
                'verbose_name': 'Información Nutricional',
                'verbose_name_plural': 'Información Nutricional',
                'db_table': 'Nutricional',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True, verbose_name='Descripción')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Roles',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('total_sin_iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total sin IVA')),
                ('total_iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='IVA (19%)')),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Descuento')),
                ('total_con_iva', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total con IVA')),
                ('canal_venta', models.CharField(choices=[('Local', 'Local'), ('UberEats', 'UberEats'), ('Instagram', 'Instagram'), ('WhatsApp', 'WhatsApp')], default='Local', max_length=20, verbose_name='Canal de Venta')),
                ('folio', models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Folio')),
                ('monto_pagado', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Monto Pagado')),
                ('vuelto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Vuelto')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('cliente_id', models.ForeignKey(db_column='cliente_id', on_delete=django.db.models.deletion.PROTECT, to='shop.clientes', verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'Ventas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100, verbose_name='Nombres')),
                ('paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('materno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Apellido Materno')),
                ('run', models.CharField(max_length=12, unique=True, verbose_name='RUN')),
                ('correo', models.EmailField(max_length=100, verbose_name='Correo Electrónico')),
                ('fono', models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono')),
                ('clave', models.CharField(blank=True, max_length=150, null=True, verbose_name='Clave')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('Direccion_id', models.ForeignKey(db_column='Direccion_id', on_delete=django.db.models.deletion.PROTECT, to='shop.direccion', verbose_name='Dirección')),
                ('Roles_id', models.ForeignKey(db_column='Roles_id', on_delete=django.db.models.deletion.PROTECT, to='shop.roles', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuarios',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=300, null=True, verbose_name='Descripción')),
                ('marca', models.CharField(blank=True, max_length=100, null=True, verbose_name='Marca')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio (sin IVA)')),
                ('caducidad', models.DateField(verbose_name='Fecha Caducidad')),
                ('elaboracion', models.DateField(blank=True, null=True, verbose_name='Fecha Elaboración')),
                ('tipo', models.CharField(help_text='Tipo de elaboración: propia o envasado', max_length=100, verbose_name='Tipo')),
                ('stock_actual', models.IntegerField(blank=True, default=0, null=True, verbose_name='Stock Actual')),
                ('stock_minimo', models.IntegerField(blank=True, default=5, null=True, verbose_name='Stock Mínimo')),
                ('stock_maximo', models.IntegerField(blank=True, default=100, null=True, verbose_name='Stock Máximo')),
                ('presentacion', models.CharField(blank=True, help_text='Unidad de almacenamiento', max_length=100, null=True, verbose_name='Presentación')),
                ('formato', models.CharField(blank=True, help_text='Cantidad por presentación', max_length=100, null=True, verbose_name='Formato')),
                ('creado', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('modificado', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('eliminado', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('Categorias_id', models.ForeignKey(db_column='Categorias_id', on_delete=django.db.models.deletion.PROTECT, to='shop.categorias', verbose_name='Categoría')),
                ('Nutricional_id', models.ForeignKey(db_column='Nutricional_id', on_delete=django.db.models.deletion.PROTECT, to='shop.nutricional', verbose_name='Info. Nutricional')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Productos',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='Movimientos_Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_movimiento', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste')], max_length=20, verbose_name='Tipo de Movimiento')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='shop.productos', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Movimiento de Inventario',
                'verbose_name_plural': 'Movimientos de Inventario',
                'db_table': 'Movimientos_Inventario',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Detalle_Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio Unitario')),
                ('descuento_pct', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Descuento (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.PROTECT, to='shop.productos', verbose_name='Producto')),
                ('venta_id', models.ForeignKey(db_column='venta_id', on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='shop.ventas', verbose_name='Venta')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalles de Venta',
                'db_table': 'Detalle_Venta',
                'ordering': ['venta_id', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Alertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_alerta', models.CharField(choices=[('Stock bajo', 'Stock bajo'), ('Vencimiento próximo', 'Vencimiento próximo')], max_length=30, verbose_name='Tipo de Alerta')),
                ('mensaje', models.CharField(max_length=255, verbose_name='Mensaje')),
                ('fecha_generada', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Generación')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('atendida', 'Atendida')], default='pendiente', help_text='Estado de la alerta: pendiente o atendida', max_length=20, verbose_name='Estado')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Fecha Modificación')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Fecha Eliminación')),
                ('producto_id', models.ForeignKey(db_column='producto_id', on_delete=django.db.models.deletion.CASCADE, to='shop.productos', verbose_name='Producto')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'db_table': 'Alertas',
                'ordering': ['-fecha_generada'],
            },
        ),
    ]
